# Generated by Django 4.1.2 on 2024-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customerinfo_myprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='peppol_receiver_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='address',
            field=models.CharField(default='123 Default St', max_length=255),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='coc_number',
            field=models.CharField(default='00000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='email_address',
            field=models.EmailField(default='john.doe@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='iban',
            field=models.CharField(default='DE89370400440532013000', max_length=34),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='peppol_sender_id',
            field=models.CharField(default='1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='postcode',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
